Create branch images to facilitate production and tests deployment
ets-cfuhrman-pfe/EvalueTonSavoir pull request #108
Opened 2024-09-18 02:53 UTC by gab9281

fixes ets-cfuhrman-pfe/EvalueTonSavoir#104

2024-09-18 15:31 UTC, fuhrmanator requested changes
As-tu testé cette action quelque part (sur un fork)?

2024-09-18 15:31 UTC, fuhrmanator commented on .github/workflows/create-branch-images.yml
> +      - '**'
Si je comprends bien, il va créer les images pour n'importe quelle branche? Ça semble overkill un peu et risque de ralentir le travail sur les branches (p.ex. pour faire un petit patch). Peux-tu proposer des noms pour les branches où ça va se faire (p.ex. devimage*) afin de limiter la création de 3 images chaque fois?

2024-09-18 15:31 UTC, fuhrmanator commented on .github/workflows/create-branch-images.yml
> +name: create-branch-images
STP documente pourquoi tu veux faire ceci (pourquoi il est important d'avoir 3 images pour chaque branche). Il y a d'autres personnes travaillant sur ce dépôt et on voudrait comprendre pourquoi cela est en place.

2024-09-18 19:01 UTC, gab9281 commented
> As-tu testé cette action quelque part (sur un fork)?

Oui sur la fork qui fait le pull en ce moment

> Si je comprends bien, il va créer les images pour n'importe quelle branche? Ça semble overkill un peu et risque de ralentir le travail sur les branches (p.ex. pour faire un petit patch). Peux-tu proposer des noms pour les branches où ça va se faire (p.ex. devimage*) afin de limiter la création de 3 images chaque fois?

Je fais une image par module de l'application, bref le routeur, le frontend et le backend d'une branche x.
Elle sont écrasées par la derniere branche - il y aura donc un seul groupe de "binaire" par branche.

Comme le deploiement actuel : 
![image](https://github.com/user-attachments/assets/cc8b472d-251d-45b0-8182-f88de320f40a)

Je le faisais In-Repo dans l'optique de permettre des deploiements rapide sur plusieurs dev car il y a prod, le dev du stagiaire et il va y avoir nos propres features branches.

2024-09-18 19:20 UTC, fuhrmanator commented
Je n'ai pas trouvé un changement pour les noms afin que les images ne soient pas créées pour chaque branche (c'est lourd). Je fais une branche chaque fois que je corrige un bogue (même dans le CSS) et je peux tester localement (npm run dev). Un docker n'est pas nécessaire et ça prend du temps pour le push pour rien. 

Je comprends qu'éventuellement vous en aurez besoin, mais propose un nom pour les branches où l'action s'embarque dans ce cas et teste-le et on pourra le mettre en place ici.

2024-09-23 18:39 UTC, fuhrmanator requested changes

2024-09-23 18:39 UTC, fuhrmanator commented on .github/workflows/create-branch-images.yml
> +      - 'main'
Salut @gab9281 je croyais que tu allais faire seulement pour dev? Un push vers main va créer les images. Est-ce juste?

2024-09-24 22:24 UTC, gab9281 commented on .github/workflows/create-branch-images.yml
> +      - 'main'
j'avaIs dit main et dev + trigger + toggle

Si vous voulez qu'on enleve main, je le fais immediatement

2024-09-24 22:30 UTC, fuhrmanator commented on .github/workflows/create-branch-images.yml
> +      - 'main'
J'aimerais comprendre pourquoi tu veux créer des images de branches s'il y a un push dans main? Ça me semble un gaspillage de ressources, mais p-e que j'ai mal compris.

2024-09-24 22:33 UTC, gab9281 commented on .github/workflows/create-branch-images.yml
> +      - 'main'
Les Oauths ne permettent pas de faire de la communication sur une addresse qui n'est pas programmée d'avance. Je ne peux pas débugger en se moment le probleme que j'ai a cause de ca et mon serveur ne supporte que Docker

2024-09-24 22:43 UTC, fuhrmanator commented on .github/workflows/create-branch-images.yml
> +      - 'main'
Tu ne réponds pas à la question :) J'ai supprimé l'option pour la branche main.

2024-09-24 22:43 UTC, fuhrmanator approved these changes

2024-09-24 22:44 UTC, merged